apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Panitnun-6243/duckduck-deployment.git"
    path: "mqtt-broker-deployment/mosquitto"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mqtt
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
