apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - dduck.panitnun.tech
      secretName: mosquitto-certs
  rules:
    - host: dduck.panitnun.tech
      http:
        paths:
          - path: /mqtt
            pathType: Prefix
            backend:
              service:
                name: mosquitto-mqtts
                port:
                  number: 8883
