apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtts
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - name: mqtts
      port: 8883
      protocol: TCP
      targetPort: 8883
