apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "duckduck-server.fullname" . }}
  labels:
    {{- include "duckduck-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "duckduck-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "duckduck-server.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "duckduck-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: MONGO_URI
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: DATABASE_NAME
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: JWT_SECRET_KEY
            - name: MQTT_BROKER
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: MQTT_BROKER
            - name: MQTT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: MQTT_CLIENT_ID
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: MQTT_USERNAME
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: duckduck-secret
                  key: MQTT_PASSWORD
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

