apiVersion: v1
kind: Service
metadata:
  name: { { include "duckduck-server.fullname" . } }
  labels: { { - include "duckduck-server.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 5050
      protocol: TCP
      name: http
  selector: { { - include "duckduck-server.selectorLabels" . | nindent 4 } }
